/**
 * Custom Prisma types for advanced type safety and utility
 *
 * This file defines custom TypeScript types and interfaces that extend or supplement
 * the types generated by Prisma. Use these types for advanced queries, DTOs, or
 * utility functions that require more specific typing than the default Prisma types.
 *
 * @file prisma.types.ts
 *
 * @example
 * ```typescript
 * import { SomeCustomType } from '../prisma/prisma.types';
 * ```
 */
// ... existing code ... 
